### ISSUE TITLE
during inference i get below error on custom  yolov4 model . Could someone help

### ISSUE THREAD

**Issue by h9945394143** [NVIDIA-AI-IOT/yolo_deepstream#25]
python3: nvdsparsebbox_Yolo.cpp:139: bool NvDsInferParseCustomYoloV4(const std::vector<NvDsInferLayerInfo>&, const NvDsInferNetworkInfo&, const NvDsInferParseDetectionParams&, std::vector<NvDsInferObjectDetectionInfo>&): Assertion `boxes.inferDims.numDims == 3' failed.

**Comment by mchi-zg** [comment]
I uploaded the sample onnx model under - https://drive.google.com/drive/folders/18TXX3c7_Of16zVeWrfCkyT4ooVMz44oW?usp=sharing

**Comment by Harish1810** [comment]
> python3: nvdsparsebbox_Yolo.cpp:139: bool NvDsInferParseCustomYoloV4(const std::vector&, const NvDsInferNetworkInfo&, const NvDsInferParseDetectionParams&, std::vector&): Assertion `boxes.inferDims.numDims == 3' failed.

I had the same issue. I solved it by using the custom bounding box parser from /opt/nvidia/deepstream/deepstream-6.1/sources/libs/nvdsinfer_customparser/ , Use the function "NvDsInferParseCustomBatchedNMSTLT"
