### ISSUE TITLE
What are topk and keeptopk parameters?

### ISSUE THREAD

**Issue by DJT777** [NVIDIA-AI-IOT/yolo_deepstream#26]
Can someone please describe to me what the "topk" and "keeptopk" parameters are? They are found in the conversion to onnx, in the arguments given for running the python script.

**Comment by mchi-zg** [comment]
Please refer to TensorRT - batchedNMSPlugin : https://github.com/NVIDIA/TensorRT/tree/main/plugin/batchedNMSPlugin
