### ISSUE TITLE
How to dynamically modify the model at runtime? For example, when you use yolov5 for one time, you will automatically switch to another model yolov7 after a period of time?

### ISSUE THREAD

**Issue by flyingfish0918** [NVIDIA-AI-IOT/yolo_deepstream#28]

**Comment by wanghr323** [comment]
Errr.....
You can init two models with tensorrt, first using yolov5,  after 1 time inference. use yolov7 to do inference instead. control with "if-else" in your program.
That sounds strange, But you can do it if you like.......
