### ISSUE TITLE
Efficient NMS option exporting to ONNX

### ISSUE THREAD

**Issue by labar90** [NVIDIA-AI-IOT/yolo_deepstream#33]
Is it possible to export to onnx with the option of efficient NMS in the quantization code?

**Comment by wanghr323** [comment]
> Is it possible to export to onnx with the option of efficient NMS in the quantization code?

Yes, It is possible, But we did not do that, the origin yolov7 repo did that, you can control with the export flag.
ref: https://github.com/WongKinYiu/yolov7#export

I will close this ISSUE, If you have any further questions, pls reopen the ISSUE

Thanks
Haoran Wang
