### ISSUE TITLE
Yolov7 instance segmentation with deepstream?

### ISSUE THREAD

**Issue by aurelm95** [NVIDIA-AI-IOT/yolo_deepstream#34]
How can I deploy an instance segmentation yolov7 model with deepstream? Once I export the model to `.trt`, I need to parse the output layers.

Is it planned to add this feature here?

Thanks!

**Comment by wanghr323** [comment]
@wyw1267

**Comment by wyw1267** [comment]
You can refer to [deepstream_tao_apps](https://github.com/NVIDIA-AI-IOT/deepstream_tao_apps). We have an example for  instance segmentation: peopleSegNet.

**Comment by wanghr323** [comment]
close as no feedback for long time
