### ISSUE TITLE
No module named 'trex'

### ISSUE THREAD

**Issue by Levi-zhan** [NVIDIA-AI-IOT/yolo_deepstream#35]
In draw-engine.py，it import trex, But this cannot be installed through pip。Is “trex“ a code?

**Comment by wanghr323** [comment]
it is here. just clone the code
`https://github.com/NVIDIA/TensorRT/tree/main/tools/experimental/trt-engine-explorer`

**Comment by wanghr323** [comment]
we have already metion this on readme, Now add a notice on `draw-engine.py` too
https://github.com/NVIDIA-AI-IOT/yolo_deepstream/commit/b36a83ba6177215383db358094ed875c975caa0c
