### ISSUE TITLE
yolov7 Error Code 3: API Usage Error (pamameter check failed at: runtime/rt/runtime.cpp)

### ISSUE THREAD

**Issue by jjzhu** [NVIDIA-AI-IOT/yolo_deepstream#37]
follow the yolov7 steps. able to generate the engine file, 

running: ./build/detect --engine==../../data/models/yolov7fp32.engine --img=./imgs/hoses.jpg,./imgs/zidane.jpg

ERROR: 3: [runtime.cpp::deserializeCudaEngine::36] Error Code 3: API Usage Error (Parameter check failed at: runtime/rt/runtime.cpp::deserializeCudaEngine::36, condition: (blob) != nullptr
)
Segmentation fault (core dumped)

**Comment by wanghr323** [comment]
Hi, @jjzhu , 
`--engine==../../data/models/yolov7fp32.engine`
> change this line to `--engine=../../data/models/yolov7fp32.engine` should fix your bug.

Thanks
Haoran Wang

**Comment by wanghr323** [comment]
close this issue, If you still meet problem, pls reopen the issue
@jjzhu
