### ISSUE TITLE
How to auto insert qdq in shortcut branch of network with residual structure ?

### ISSUE THREAD

**Issue by lixhk** [NVIDIA-AI-IOT/yolo_deepstream#38]
I see you define some rules to align scale settings and batch rename module(from torch.nn. to quant_nn.), very good design !  

Now if I donot modify the forward code, I try to use torch.fx to replace [operator.add, torch.add, "add"] (as call_function) to call_module  (I custom a nn.module which include  `residual_quantizer` 
           self.residual_quantizer = quant_nn.TensorQuantizer(quant_nn.QuantConv2d.default_quant_desc_input) 
) 

How to auto insert qdq in shortcut branch of network with residual structure,
Can you give me some advice or other method,  Ths ?

**Comment by wanghr323** [comment]
We will working on this feature if we got a chance.

**Comment by lixhk** [comment]
Thanks, Now I have solve it， closed

**Comment by lix19937** [comment]
@wanghr323  In PTQ mode, TensorRT(8.x, 9.x) will have the best performance,  But for tensorrt10.x, how to get the best performance by tensorrt ?   Sometimes, `trtexec --onnx=fp32.onnx --best` method takes longer inference time than FP16 .
