### ISSUE TITLE
shared memory using Jetson devices

### ISSUE THREAD

**Issue by jjzhu** [NVIDIA-AI-IOT/yolo_deepstream#39]
in pushImg, we have to copy memory from cpu to gpu or device to device. for Jetson devices, such as AGX orin, can we save this step by leveraging shared memory.

**Comment by wanghr323** [comment]
Yeah, good idea, Will add this feature once we have time.

**Comment by wanghr323** [comment]
we won't develop this feature as this sample mainly guidance for QAT and deepstream deploy
