### ISSUE TITLE
batch inference fps calculation

### ISSUE THREAD

**Issue by victorzhu-epirus** [NVIDIA-AI-IOT/yolo_deepstream#40]
just wondering how the fps is calculated for the batch 16 case. It reported https://github.com/NVIDIA-AI-IOT/yolo_deepstream/tree/main/yolov7_qat the fps is 168 for FP16. Does this mean for each batch of 16 it will take 168/16=10ms?

**Comment by wanghr323** [comment]
fps : frame per second, fps is 168 for FP16. that means one image will  take 1/168 s, one batch will take 16/168 s.

**Comment by wanghr323** [comment]
close as no feedback for long time
